### ISSUE TITLE
Posts with <!-- more --> cannot be pushed to wordpress

### ISSUE THREAD

**Issue by lincolnthree** [brool/wordpress-shuffle#2]
When dealing with posts that have "more text" - such as: https://github.com/ocpsoft/ocpsoft.org/blob/master/2012/03/secure-your-applications-url-based-attacks-are-real-and-dangerous

It is possible to pull down new changes, but not possible to push new ones. I believe this has something to do with the parsing of the saved file, and the position of the ".mt_text_more" (and related) attributes:

Error follows:

```
     $ python wp.py push
     Traceback (most recent call last):
       File "wp.py", line 261, in <module>
         xml.edit_post(p.id(), p.as_dict())
       File "wp.py", line 40, in edit_post
         def edit_post(self, post_id, post): return self.xrpc.metaWeblog.editPost(post_id, self.user, self.password,          post, True)
       File "/usr/lib/python2.6/xmlrpclib.py", line 1199, in __call__
         return self.__send(self.__name, args)
       File "/usr/lib/python2.6/xmlrpclib.py", line 1489, in __request
         verbose=self.__verbose
       File "/usr/lib/python2.6/xmlrpclib.py", line 1253, in request
         return self._parse_response(h.getfile(), sock)
       File "/usr/lib/python2.6/xmlrpclib.py", line 1392, in _parse_response
         return u.close()
       File "/usr/lib/python2.6/xmlrpclib.py", line 838, in close
         raise Fault(**self._stack[0])
     xmlrpclib.Fault: <Fault 404: 'Invalid post ID.'>
```

**Comment by lincolnthree** [comment]
I am not really super familiar with python, or I would take a shot at debugging this, but... I figured I'd ask before going too far. PS. Very nice little tool. I think it's very close to being a perfect solution for allowing open-source contributions to articles via Git.

Just need pages support and this issue worked out!

**Comment by lincolnthree** [comment]
Failed build output, for reference: http://ci.ocpsoft.org/job/ocpsoft-sync-git2wp/lastFailedBuild/console

**Comment by lincolnthree** [comment]
Yeah, I think this is due to the fact that the `.mt_text_more` attribute contains a whole lot of stuff that throws off the attribute parsing:

```
Traceback (most recent call last):
  File "wp.py", line 259, in <module>
    (created, changed) = get_changed_files(basedir, xml, maxUnchanged=numToCheck)
  File "wp.py", line 154, in get_changed_files
    if xml_post.signature() != local_post.signature():
  File "wp.py", line 130, in signature
    return md5.md5(str(self).strip()).digest()
  File "wp.py", line 66, in __str__
    print self.post['postid']
KeyError: 'postid'
```

**Comment by lincolnthree** [comment]
Update. I got this working by switching to XML-like delimiters in the blog files. However, it's now nearly 6am and I have yet to sleep, so... I think I'll go do that.

**Comment by brool** [comment]
Yeah, I'm able to reproduce this.  I think the cleanest would be to convert .wp_text_more back into the original format (i.e.,  embedded in the body) as it would be most invisible -- let me take a look later today and see if I can get a patch in.  Sorry for your difficulties, and thanks for the bug report!

**Comment by lincolnthree** [comment]
You're welcome - note, I already fixed this in a way that I think is more sustainable than the .wp_text.... parameters (see pull request.) Let me know what you think.
